# 01 Memuat dan Memeriksa Dataset

## Hasil pembelajaran

Setelah notebook ini, Anda dapat:

- Memuat file CSV ke dalam Pandas DataFrame;
- Memeriksa struktur dataset (baris, kolom, tipe data);
- Memahami ringkasan statistik dasar dari setiap variabel;
- Mengidentifikasi fitur kategoris dan numerik;
- Merencanakan langkah pembersihan data berikutnya.

### Penanda Sel Kode
- `# RUN-NOW`: dapat langsung dijalankan.
- `# LEARNER-TASK`: ubah bagian bertanda [UBAH]/[ANDA TULIS], lalu jalankan.

## Mengapa memuat data dengan benar penting?

Sebelum analisis apa pun, Anda harus:

1. **Tahu apa yang ada** - berapa baris dan kolom?
2. **Tahu tipe data** - apakah pandas memperlakukan kolom sebagai angka, teks, atau kategori?
3. **Tahu ada apa saja** - apakah ada nilai hilang? Duplikat? Nilai ekstrim?
4. **Tahu kemana** - file sudah tersimpan di mana dalam struktur folder?

Misi notebook ini: Jawab semua pertanyaan di atas dengan data latihan kami.

## Impor library

In [86]:
# RUN-NOW: Jalankan sel ini apa adanya.
import pandas as pd
import numpy as np
from pathlib import Path

print("Library siap")

Library siap

## Tentukan jalur file

In [87]:
# RUN-NOW: Jalankan sel ini apa adanya.
# Gunakan Path untuk portabilitas lintas platform
candidate_paths = [
    Path("data/synthetic/synthetic_student_performance.csv"),
    Path("../data/synthetic/synthetic_student_performance.csv"),
    Path("/workspaces/metpen-ai-lab/data/synthetic/synthetic_student_performance.csv"),
]

data_file = next((p for p in candidate_paths if p.exists()), None)

if data_file is None:
    raise FileNotFoundError(
        "File data tidak ditemukan. Periksa folder data/synthetic atau jalankan dari root project."
    )

print(f"✓ File ditemukan: {data_file.resolve()}")

✓ File ditemukan: /workspaces/metpen-ai-lab/data/synthetic/synthetic_student_performance.csv

## Memuat data ke DataFrame

In [88]:
# RUN-NOW: Jalankan sel ini apa adanya.
# Baca CSV menjadi Pandas DataFrame
df = pd.read_csv(data_file)

print("✓ Data berhasil dimuat")
print(f"Bentuk dataset: {df.shape[0]} baris × {df.shape[1]} kolom")

✓ Data berhasil dimuat
Bentuk dataset: 2012 baris × 20 kolom

## Lihat beberapa baris pertama (head)

In [89]:
# RUN-NOW: Jalankan sel ini apa adanya.
df.head(10)

,student_id,cohort_year,program,semester,attendance_rate,assignment_score,quiz_average,midterm_score,final_exam_score,lms_logins,study_hours_per_week,internet_access,part_time_work_hours,commute_minutes,ai_tool_usage_frequency,previous_gpa,final_grade,passed,submission_delay_days,missing_reason_flag
0,S100000,2023,Computer Science,6,84.15,83.08,82.99,100.00,100.00,59,14.32,stable,0.00,47.59,sometimes,3.30,90.46,1,2.0,none
1,S100001,2022,Economics,6,87.77,94.66,74.36,100.00,100.00,69,8.67,stable,7.20,2.92,very_often,3.50,94.00,1,0.0,none
2,S100002,2024,Public Health,3,77.59,73.19,71.43,95.27,100.00,33,4.55,limited,0.35,47.33,often,3.40,85.61,1,2.0,none
3,S100003,2023,Computer Science,3,86.13,78.00,75.35,92.44,94.98,47,7.16,stable,8.34,4.87,sometimes,3.03,90.48,1,1.0,none
4,S100004,2021,Education,8,100.00,98.97,86.06,100.00,100.00,48,8.06,stable,11.44,32.88,often,4.00,100.00,1,1.0,none
5,S100005,2024,Public Health,7,76.90,85.21,69.37,100.00,86.04,70,7.32,stable,16.44,14.06,sometimes,2.84,78.03,1,0.0,none
6,S100006,2023,Economics,4,79.61,92.22,63.89,100.00,92.16,82,16.25,limited,2.03,60.76,sometimes,2.28,83.05,1,0.0,none
7,S100007,2023,Education,2,70.29,69.41,69.55,89.90,92.67,61,15.34,stable,12.80,14.17,rarely,2.36,80.87,1,1.0,self_report_missing
8,S100008,2021,Education,3,63.09,96.93,76.62,100.00,100.00,70,21.15,limited,10.10,5.30,often,3.66,91.29,1,1.0,none
9,S100009,2022,Computer Science,5,83.81,79.74,72.05,100.00,96.27,60,7.57,stable,12.43,37.40,sometimes,2.97,85.29,1,2.0,none

## Lihat beberapa baris terakhir (tail)

In [90]:
# RUN-NOW: Jalankan sel ini apa adanya.
df.tail(5)

,student_id,cohort_year,program,semester,attendance_rate,assignment_score,quiz_average,midterm_score,final_exam_score,lms_logins,study_hours_per_week,internet_access,part_time_work_hours,commute_minutes,ai_tool_usage_frequency,previous_gpa,final_grade,passed,submission_delay_days,missing_reason_flag
2007,S101378,2023,Economics,7,89.65,81.22,74.86,100.00,100.00,47,5.25,stable,7.54,20.56,rarely,2.90,89.81,1,1.0,none
2008,S101949,2024,Psychology,5,76.94,88.96,68.20,98.71,NaN,50,6.73,limited,14.33,26.17,rarely,3.63,89.47,1,2.0,none
2009,S100535,2022,Economics,7,90.04,87.49,74.75,100.00,100.00,50,10.24,limited,6.76,88.26,rarely,2.97,88.82,1,3.0,none
2010,S100636,2023,Economics,1,82.68,66.50,72.16,100.00,100.00,37,11.75,stable,4.41,66.32,rarely,2.96,87.50,1,2.0,none
2011,S101687,2023,Public Health,4,91.25,84.12,60.03,100.00,96.17,68,9.79,limited,16.49,6.75,rarely,3.02,85.14,1,2.0,none

## Informasi struktur data

In [91]:
# RUN-NOW: Jalankan sel ini apa adanya.
# Tampilkan informasi detail: nama kolom, tipe data, non-null count
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2012 entries, 0 to 2011
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               2012 non-null   str
 1   cohort_year              2012 non-null   int64
 2   program                  2012 non-null   str
 3   semester                 2012 non-null   int64
 4   attendance_rate          2012 non-null   float64
 5   assignment_score         2012 non-null   float64
 6   quiz_average             2012 non-null   float64
 7   midterm_score            2012 non-null   float64
 8   final_exam_score         1973 non-null   float64
 9   lms_logins               2012 non-null   int64
 10  study_hours_per_week     2008 non-null   float64
 11  internet_access          2012 non-null   str
 12  part_time_work_hours     2012 non-null   float64
 13  commute_minutes          2012 non-null   float64
 14  ai_tool_usage_frequency  2012 non-null   str
 15  previous_gpa             2012 non-null   float64
 16  final_grade              2012 non-null   float64
 17  passed                   2012 non-null   int64
 18  submission_delay_days    2012 non-null   float64
 19  missing_reason_flag      2012 non-null   str
dtypes: float64(11), int64(4), str(5)
memory usage: 314.5 KB

### Apa artinya output di atas?

- **Column**: Nama variabel
- **Non-Null Count**: Berapa banyak nilai yang ada (bukan NaN/hilang)
- **Dtype**: Tipe data (float64 = angka desimal, int64 = integer, object = teks/mixed)

Perhatikan: ada kolom dengan nilai hilang jika `Non-Null Count < total rows`.

## Ringkasan statistik deskriptif dasar

In [92]:
# RUN-NOW: Jalankan sel ini apa adanya.
# describe() menampilkan: count, mean, std, min, 25%, 50%, 75%, max
df.describe()

,cohort_year,semester,attendance_rate,assignment_score,quiz_average,midterm_score,final_exam_score,lms_logins,study_hours_per_week,part_time_work_hours,commute_minutes,previous_gpa,final_grade,passed,submission_delay_days
count,2012.000000,2012.000000,2012.000000,2012.000000,2012.000000,2012.000000,1973.000000,2012.000000,2008.000000,2012.000000,2012.000000,2012.000000,2012.000000,2012.000000,2012.000000
mean,2022.498509,4.517893,81.470209,82.416098,73.906476,98.154702,96.650558,53.636183,11.216922,10.169056,34.531774,3.004448,86.906844,0.999006,1.582505
std,1.035183,2.254159,10.012656,9.196634,8.927796,4.111809,5.734376,11.632011,4.475773,6.409869,18.123606,0.450649,7.267726,0.031520,1.240640
min,2021.000000,1.000000,51.200000,56.300000,43.990000,55.210000,61.580000,18.000000,0.000000,0.000000,0.000000,1.500000,57.800000,0.000000,0.000000
25%,2022.000000,3.000000,74.365000,76.040000,67.645000,98.867500,94.960000,46.000000,8.077500,5.570000,21.970000,2.700000,82.267500,1.000000,1.000000
50%,2022.000000,5.000000,81.690000,82.645000,73.805000,100.000000,100.000000,53.000000,11.130000,9.840000,33.910000,3.000000,87.355000,1.000000,1.000000
75%,2023.000000,6.000000,88.612500,88.842500,80.142500,100.000000,100.000000,61.000000,14.292500,14.442500,46.942500,3.310000,92.330000,1.000000,2.000000
max,2024.000000,8.000000,100.000000,100.000000,100.000000,100.000000,100.000000,92.000000,24.790000,38.180000,96.850000,4.000000,100.000000,1.000000,7.000000

### Interpretasi output di atas

- **count**: Jumlah nilai non-missing untuk setiap kolom
- **mean**: Rata-rata
- **std**: Standar deviasi (ukuran penyebaran)
- **min/max**: Nilai terendah dan tertinggi
- **25%/50%/75%**: Kuartil (persentil ke-25, ke-50, ke-75)

**Apa yang kami perhatikan?** Apakah ada nilai ekstrim atau tidak realistis?

## Periksa tipe data setiap kolom

In [93]:
# RUN-NOW: Jalankan sel ini apa adanya.
print("Tipe data setiap kolom:")
print(df.dtypes)

print("\n" + "=" * 50)
print("Kolom numerik:", df.select_dtypes(include=["number"]).columns.tolist())
print("Kolom kategoris:", df.select_dtypes(include=["object", "string"]).columns.tolist())

Tipe data setiap kolom:
student_id                     str
cohort_year                  int64
program                        str
semester                     int64
attendance_rate            float64
assignment_score           float64
quiz_average               float64
midterm_score              float64
final_exam_score           float64
lms_logins                   int64
study_hours_per_week       float64
internet_access                str
part_time_work_hours       float64
commute_minutes            float64
ai_tool_usage_frequency        str
previous_gpa               float64
final_grade                float64
passed                       int64
submission_delay_days      float64
missing_reason_flag            str
dtype: object

==================================================
Kolom numerik: ['cohort_year', 'semester', 'attendance_rate', 'assignment_score', 'quiz_average', 'midterm_score', 'final_exam_score', 'lms_logins', 'study_hours_per_week', 'part_time_work_hours', 'commute_minutes', 'previous_gpa', 'final_grade', 'passed', 'submission_delay_days']
Kolom kategoris: ['student_id', 'program', 'internet_access', 'ai_tool_usage_frequency', 'missing_reason_flag']

## Nilai unik dalam kolom kategoris

In [94]:
# RUN-NOW: Jalankan sel ini apa adanya.
# Lihat kategori dalam beberapa kolom
print("Nilai unik dalam 'program':")
print(df["program"].unique())
print(f"Jumlah: {df['program'].nunique()}")

print("\nNilai unik dalam 'internet_access':")
print(df["internet_access"].unique())
print(f"Jumlah: {df['internet_access'].nunique()}")

print("\nNilai unik dalam 'ai_tool_usage_frequency':")
print(df["ai_tool_usage_frequency"].unique())
print(f"Jumlah: {df['ai_tool_usage_frequency'].nunique()}")

Nilai unik dalam 'program':
<StringArray>
['Computer Science', 'Economics', 'Public Health', 'Education', 'Psychology']
Length: 5, dtype: str
Jumlah: 5

Nilai unik dalam 'internet_access':
<StringArray>
['stable', 'limited', 'unstable']
Length: 3, dtype: str
Jumlah: 3

Nilai unik dalam 'ai_tool_usage_frequency':
<StringArray>
['sometimes', 'very_often', 'often', 'rarely', 'never']
Length: 5, dtype: str
Jumlah: 5

## Hitung frekuensi kategori

In [95]:
# RUN-NOW: Jalankan sel ini apa adanya.
# Berapa banyak mahasiswa per program?
print("Distribusi per program:")
print(df["program"].value_counts())

print("\nDistribusi internet_access:")
print(df["internet_access"].value_counts())

print("\nDistribusi passed (lulus/tidak):")
print(df["passed"].value_counts())

Distribusi per program:
program
Education           454
Computer Science    437
Economics           418
Psychology          404
Public Health       299
Name: count, dtype: int64

Distribusi internet_access:
internet_access
stable      1430
limited      407
unstable     175
Name: count, dtype: int64

Distribusi passed (lulus/tidak):
passed
1    2010
0       2
Name: count, dtype: int64

## Periksa nilai hilang (missing values)

In [96]:
# RUN-NOW: Jalankan sel ini apa adanya.
# Hitung missing values
missing = df.isnull().sum()
missing_percent = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "Kolom": missing.index,
    "Jumlah NaN": missing.values,
    "Persentase": missing_percent.values,
})

# Hanya tampilkan kolom dengan nilai hilang
missing_df = missing_df[missing_df["Jumlah NaN"] > 0].sort_values("Jumlah NaN", ascending=False)

if len(missing_df) == 0:
    print("✓ Tidak ada nilai hilang (missing values) dalam dataset")
else:
    print("Kolom dengan nilai hilang:")
    print(missing_df)

Kolom dengan nilai hilang:
                   Kolom  Jumlah NaN  Persentase
8       final_exam_score          39    1.938370
10  study_hours_per_week           4    0.198807

## Ringkasan hasil inspeksi

In [97]:
# RUN-NOW: Jalankan sel ini apa adanya.
print("📊 RINGKASAN DATASET")
print(
    f"""\n✓ Ukuran: {df.shape[0]} baris × {df.shape[1]} kolom
✓ Variabel numerik: {len(df.select_dtypes(include=['number']).columns)}
✓ Variabel kategoris: {len(df.select_dtypes(include=['object', 'string']).columns)}
✓ Nilai hilang: {df.isnull().sum().sum()} (dalam {(df.isnull().sum() > 0).sum()} kolom)
✓ Duplikat baris: {df.duplicated().sum()}
"""
)

📊 RINGKASAN DATASET

✓ Ukuran: 2012 baris × 20 kolom
✓ Variabel numerik: 15
✓ Variabel kategoris: 5
✓ Nilai hilang: 43 (dalam 2 kolom)
✓ Duplikat baris: 12

## Tugas Anda

Sebelum lanjut ke notebook berikutnya, jawab pertanyaan ini:

1. **Kolom apa yang memiliki nilai hilang?** Berapa persentasenya?
2. **Kolom numerik apa yang memiliki range yang tidak realistis?** (Misalnya, nilai negatif ketika harusnya positif)
3. **Ada berapa mahasiswa yang lulus vs tidak lulus?**
4. **Program apa yang memiliki jumlah mahasiswa paling sedikit?**

Tulis jawaban Anda di kertas atau comment di sel ini.

In [98]:
print("JAWABAN TUGAS")
print("=" * 50)

# 1) Kolom dengan nilai hilang
missing_columns = missing_df.copy() if 'missing_df' in globals() else pd.DataFrame()
if len(missing_columns) == 0:
    print("\n1) Kolom dengan nilai hilang: tidak ada.")
else:
    print("\n1) Kolom dengan nilai hilang:")
    for _, row in missing_columns.iterrows():
        print(f"- {row['Kolom']}: {int(row['Jumlah NaN'])} nilai hilang ({row['Persentase']:.2f}%)")

# 2) Kolom numerik yang memiliki range tidak realistis
expected_ranges = {
    "attendance_rate": (0, 100),
    "assignment_score": (0, 100),
    "quiz_average": (0, 100),
    "midterm_score": (0, 100),
    "final_exam_score": (0, 100),
    "lms_logins": (0, None),
    "study_hours_per_week": (0, None),
    "part_time_work_hours": (0, None),
    "commute_minutes": (0, None),
    "previous_gpa": (0, 4.0),
    "final_grade": (0, 100),
    "submission_delay_days": (0, None),
}

unrealistic_columns = []
for column, (lower_bound, upper_bound) in expected_ranges.items():
    if column not in df.columns:
        continue
    series = df[column].dropna()
    invalid_mask = series < lower_bound
    if upper_bound is not None:
        invalid_mask = invalid_mask | (series > upper_bound)
    if invalid_mask.any():
        unrealistic_columns.append(column)

if len(unrealistic_columns) == 0:
    print("\n2) Kolom numerik yang memiliki range tidak realistis: tidak ada.")
else:
    print("\n2) Kolom numerik yang memiliki range tidak realistis:")
    for column in unrealistic_columns:
        print(f"- {column}")

# 3) Distribusi mahasiswa yang lulus vs tidak lulus
print("\n3) Distribusi passed (lulus/tidak):")
passed_counts = df["passed"].value_counts().sort_index()
for label, count in passed_counts.items():
    status = "lulus" if label == 1 else "tidak lulus"
    print(f"- {status}: {count}")

# 4) Program dengan jumlah mahasiswa paling sedikit
program_counts = df["program"].value_counts()
least_program = program_counts.idxmin()
least_count = int(program_counts.min())
print("\n4) Program dengan jumlah mahasiswa paling sedikit:")
print(f"- {least_program}: {least_count} mahasiswa")

JAWABAN TUGAS
==================================================

1) Kolom dengan nilai hilang:
- final_exam_score: 39 nilai hilang (1.94%)
- study_hours_per_week: 4 nilai hilang (0.20%)

2) Kolom numerik yang memiliki range tidak realistis: tidak ada.

3) Distribusi passed (lulus/tidak):
- tidak lulus: 2
- lulus: 2010

4) Program dengan jumlah mahasiswa paling sedikit:
- Public Health: 299 mahasiswa

## Catatan tentang data sintetis

⚠️ **Penting**: Data ini adalah **sintetis** - dibuat oleh algoritma, bukan data mahasiswa nyata.

Keuntungan:
- Aman untuk latihan (tidak ada data pribadi nyata)
- Dapat direproduksi setiap saat
- Properti dapat dikontrol dengan tepat

Keterbatasan:
- Tidak mewakili kompleksitas data dunia nyata
- Hubungan variabel mungkin terlalu sederhana
- Pola tidak selalu realistis

**Gunakan untuk belajar workflow, bukan untuk kesimpulan tentang perilaku mahasiswa nyata.**

## Langkah berikutnya

✓ Anda sudah mengenal dataset kami.

→ Notebook berikutnya (`02_data_quality_cleaning.ipynb`): Identifikasi masalah kualitas data dan perbaiki.